export const ActionTypes={

    GET_ALL_STUDENT:'GET_ALL_STUDENT',
    ADD_STUDENT:'ADD_STUDENT',
    GET_STUDENT_BYID:'GET_STUDENT_BYID',
    UPDATE_STUDENT:'UPDATE_STUDENT',
    DELETE_STUDENT:'DELETE_STUDENT'



}